# Generated by Django 3.2.21 on 2023-09-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='TEMP_DEFAULT', editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
